name: Cancel Workflows
on:
  workflow_run:
    workflows: ["Sleep"]
    types:
      - requested
jobs:
  cancel:
    name: Cancel workflows
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.9.0
      with:
        workflow_id: ${{ github.event.workflow.id }}