# This is a basic workflow to help you get started with Actions

name: CI

on: [push,pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        id: hello
        uses: ./
        with:
          args: docs/* ci/jenkins/* *.md hack/.notableofcontents
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
  print_context_job:
    runs-on: ubuntu-latest
    name: A job to print context
    steps:
      - name: Echo github obj
        run: echo "${{ toJson(github) }}"
      - name: Echo env obj
        run: echo "${{ toJson(env) }}"
      - name: Echo job obj
        run: echo "${{ toJson(job) }}"
      - name: Echo steps obj
        run: echo "${{ toJson(steps) }}"
      - name: Echo runner obj
        run: echo "${{ toJson(runner) }}"
      - name: Echo needs obj
        run: echo "${{ toJson(needs) }}"